### ISSUE TITLE
"this expression cannot run in the group_by context" error 

### ISSUE THREAD

**Issue by bn-c** [ion-elgreco/polars-hash#26]
```
2024-07-29 14:22:57,515 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Error from Python:Traceback (most recent call last):
  File "/tmp/test-polars-big.py", line 82, in <module>
    main()
  File "/tmp/test-polars-big.py", line 44, in main
    df = df.with_columns(
  File "/home/spark/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8858, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/spark/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2026, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: this expression cannot run in the group_by context

Error originated in expression: 'col("")./home/spark/.local/lib/python3.10/site-packages/polars_hash/_internal.abi3.so:md5()'
```

Polars version: 1.3.0

Related code snippet
```python
    df = df.with_columns( 
      pl.col("email")
          .str.split('@')
          .list.eval(plh.col("").nchash.md5().str.slice(0,pl.element().str.len_chars()))
          .list.join('@'),
    )
```
I am not too sure what is the right way to use `plh` with `df.with_columns` but it seems to have a conflict when upgrading from polars 1.2.1 to 1.3.0

**Comment by bn-c** [comment]
Related issues from polars that I've found
https://github.com/pola-rs/polars/issues/17356
https://github.com/pola-rs/polars/issues/17749

**Comment by bn-c** [comment]
Thank you for the quick response!
I am new to polars, and after seeing your examples in README.md, it appears that `import polars_hash as plh` might not be necessary? Or at least the use of `plh`. Since I am not too sure how polars Expression plugins work.

**Comment by bn-c** [comment]
Unfortunately it appears I still encounter the same error
```
2024-07-29 14:53:44,010 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Error from Python:Traceback (most recent call last):
  File "/tmp/test-polars-big.py", line 80, in <module>
    main()
  File "/tmp/test-polars-big.py", line 44, in main
    df = df.with_columns(
  File "/home/spark/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8858, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/spark/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2026, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: this expression cannot run in the group_by context

Error originated in expression: 'col("")./home/spark/.local/lib/python3.10/site-packages/polars_hash/_internal.abi3.so:md5()'
```

**Comment by ion-elgreco** [comment]
@bn-c can you give me a small sample dataframe, so that I can run your polars code?

**Comment by bn-c** [comment]
@ion-elgreco  Another thing I've noticed, that the above code works with polars 1.2.1, but not with the newly released 1.3.0. 
Would you reckon this is a polars bug?

Here's the attached sample: [sample.csv](https://github.com/user-attachments/files/16415385/sample.csv)

**Comment by ion-elgreco** [comment]
> @ion-elgreco Another thing I've noticed, that the above code works with polars 1.2.1, but not with the newly released 1.3.0. Would you reckon this is a polars bug?
> 
> Here's the attached sample: [sample.csv](https://github.com/user-attachments/files/16415385/sample.csv)

Can you send a small sample as code please? Just a pl.DataFrame({})

**Comment by ion-elgreco** [comment]
@bn-c  this was a regression in polars, should be fine now. Sorry for late followup, I forgot to respond to this thread
